config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists do
    resources :bookmarks, only: %i[new create show index]
  end
  resources :bookmarks, only: %i[destroy]
  resources :movies, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Comment was successfully created.'
    else
      puts @bookmark.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]
  def index
    @lists = List.all
  end

  def show
    @movie = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created!', status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, notice: 'List was successfully destroyed.', status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">

      <%= link_to "Watch List", lists_path, class: "navbar-brand" %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div class="ms-auto flex">

          <%= link_to "My list", lists_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2" %>
          <%= link_to "New list", new_list_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2" %>

        </div>

      </div>

    </div>

  </nav>

app/views/bookmarks/new.html.erb
<%= render "navbar" %>

<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new movie to <%= @list.name %> list</h1>
        <div class="mt-3">

          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.association :movie %>
            <%= f.input :comment %>
            <%= f.submit "Add", class: "btn btn-primary"%>
          <% end %>
          <br>
          <%= link_to "Cancel and go back to List", list_path(@list), class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/lists/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">

    <div class="container-fluid">

      <%= link_to lists_path, class: "navbar-brand", style: "color: white;" do %>
        <i class="fa-solid fa-film" style= "color: red"></i> Watch my movie List"
      <% end %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div class="ms-auto flex">

          <%= link_to "Movies", movies_path, class: "btn btn-flat" %>
          <%= link_to "My list", lists_path, class: "btn btn-flat" %>
          <%= link_to "New list", new_list_path, class: "btn btn-flat" %>

        </div>

      </div>

    </div>

  </nav>

app/views/lists/index.html.erb
<%= render "navbar" %>



<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?cinema);">
  <div class="container text-center">
    <h1>Movie lists</h1>
    <p class="count"><%= @lists.count %> lists</p>
  </div>
</div>


<div class="container">

  <div class="d-flex justify-content-between pt-4 pb-4">
    <h2>My Lists</h2>
    <%= link_to "Create a movie list", new_list_path, class: "btn btn-flat-green" %>
  </div>


  <div class="cards-category">
    <% @lists.each do |list| %>
    <% if list.photo.present? %>
      <div class="card-category" style="background-image: url('<%= cl_image_path list.photo.key %>')">
        <%= link_to list_path(list), class: "card-category-cloud" do %>
          <%= list.name %>
        <% end %>
      </div>

    <% else %>
      <%= link_to list_path(list), class: "card-category", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{list.image})" do %>
        <%= list.name %>
      <% end %>
      <% end %>
    <% end %>
  </div>


</div>



<%# Test cloudinary %>
<%# <%= cl_image_tag "hvgqhl4jdkhdv32xvowl", alt: "San Francisco", width: 400, %>
  <%# height: 300, crop: :fill %>

<%# <%= cl_image_tag "g1kkb9mzzkk8hltlhamj", alt: "San Francisco", width: 150, %>
  <%# height: 150, crop: :thumb, gravity: :face %>

app/views/lists/new.html.erb
<%= render "navbar" %>

<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new List</h1>
        <div class="mt-3">
          <%= render "form", list: @list %>
          <br>
          <%= link_to "Cancel and go back to Lists", lists_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "navbar" %>

<div class="banner" style="background-image: url('<%= cl_image_path @list.photo.key %>');">
  <div class="container text-center">
    <h1><%= @list.name %> movies</h1>
    <p class="count"><%= @list.movies.count %> movies</p>
  </div>
</div>

<div class="container">


  <div class="d-flex justify-content-end pt-4 pb-4">
    <%= link_to "add a movie", new_list_bookmark_path(@list), class: "btn btn-flat-green padding-right: 0;" %>
  </div>

  <div class="cards">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card">
        <%= image_tag bookmark.movie.poster_url, alt: "Movie poster", class: "card-img-top" %>
        <div class="card-body">

          <div class="card-title">
            <h2><%= link_to bookmark.movie.title, movie_path(bookmark.movie) %></h2>
            <i class="fa-solid fa-circle"></i>
            <%= bookmark.movie.rating %>
            <i class="fa-solid fa-star" style="color: #FFD43B;"></i>
          </div>

          <p class="overview"><%= bookmark.movie.overview %></p>

          <div class="card-bottom">
            <p style="font-weight: bold;"><i class="fa-solid fa-quote-left" style="color: #000000;"></i> <%= bookmark.comment %> by Ben</p>
            <div class="delete-icon">
              <%= link_to '<i class="fa-solid fa-trash-can" style="color: #ea1a1a; font-size: 24px;"></i>'.html_safe,
              bookmark_path(bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          </div>

        </div>
      </div>
    <% end %>
  </div>

  <div class="option-list">
    <%= link_to "Delete list", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-flat" %>
    <%= link_to "Back to lists", lists_path, class: "btn btn-flat" %>
  </div>

</div>

app/views/movies/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">

    <div class="container-fluid">

      <%= link_to lists_path, class: "navbar-brand", style: "color: white;" do %>
        <i class="fa-solid fa-film" style= "color: red"></i> Watch my movie List"
      <% end %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div class="ms-auto flex">

          <%= link_to "Movies", movies_path, class: "btn btn-flat" %>
          <%= link_to "My list", lists_path, class: "btn btn-flat" %>
          <%= link_to "New list", new_list_path, class: "btn btn-flat" %>

        </div>

      </div>

    </div>

  </nav>

app/views/movies/index.html.erb
<%= render "navbar" %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?cinema);">
  <div class="container text-center">
    <h1>Movies</h1>
  </div>
</div>

<div class="container">

<div class="cards">
  <% @movies.each do |movie| %>
    <div class="card">
      <%= link_to movie.title, movie_path(movie),class: "card-category", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{movie.poster_url})"  %>
    </div>
  <% end %>
</div>

</div>

app/views/movies/show.html.erb
<%= render "navbar" %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?cinema);">
  <div class="container text-center">
    <h1>Movies</h1>
  </div>
</div>

<div class="container">
<div class="card-product">
  <img src="<%= @movie.poster_url %>" alt="movie poster", style="width: 280px;"/>
  <div class="card-product-infos">
    <h2><%= @movie.title %></h2>
    <p><%= @movie.overview %></p>
  </div>
  <%= link_to "Back to movies", movies_path, class: "btn btn-flat" %>
</div>
</div>